package com.ahmetgeze.flightticket.model.exception;

public enum ExceptionCode {
    AIRPORT_SAVE_ERR_1,
    AIRPORT_SEARCH_ERR_1,
    AIRPORT_GET_ERR_1,
    ROUTE_SAVE_ERR_1,
    ROUTE_GET_ERR_1,
    ROUTE_SEARCH_ERR_1,
    ROUTE_SEARCH_ERR_2,
    ROUTE_SEARCH_ERR_3,
    ROUTE_FILTER_ERR_1,
    ROUTE_FILTER_ERR_2,
    AIRLINES_COMPANY_SAVE_ERR_1,
    AIRLINES_COMPANY_GET_ERR_1,
    AIRLINES_SEARCH_ERR_1,
    FLIGHT_RECORD_SAVE_ERR_1,

    NULL_INPUT_ERR,
    EQUAL_DEPERTURE_ARRIVAL_ROUTE_ID_ERR_1,
    FLIGHT_GET_ERR_1,
    FLIGHT_RECORD_DATE_ERR_1,
    FLIGHT_RECORD_SEAT_COUNT_ERR_1,
    FLIGHT_RECORD_SEARCH_ERR_1,
    NEXT_DATE_CONVERT_ERR1

}
