package com.ahmetgeze.flightticket.model.exception;

public enum ExceptionCode {
    AIRPORT_SAVE_ERR_1,
    AIRPORT_SEARCH_ERR_1,
    AIRPORT_GET_ERR_1,
    ROUTE_SAVE_ERR_1,
    ROUTE_SEARCH_ERR_1,
    ROUTE_SEARCH_ERR_2,
    ROUTE_SEARCH_ERR_3,
    ROUTE_FILTER_ERR_1,
    ROUTE_FILTER_ERR_2,
    AIRLINES_COMPANY_SAVE_ERR_1,
    AIRLINES_SEARCH_ERR_1,
    FLIGHT_RECORD_SAVE_ERR_1,

    NULL_INPUT_ERR,
    EQUAL_DEPERTURE_ARRIVAL_ROUTE_ID
}
